apiVersion: v1
kind: PersistentVolume
metadata:
  name: tgtg-scanner-pv
spec:
  capacity:
    storage: 5Mi
  volumeMode: Filesystem
  accessModes:
  - ReadOnlyMany
  persistentVolumeReclaimPolicy: Delete
  storageClassName: local-storage
  local:
    path: /opt/tgtg-scanner/tokens
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: Exists
