apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tgtg-scanner-pvc
spec:
  accessModes:
    - ReadOnlyMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 5Mi
  storageClassName: local-storage
